import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import '@mantine/core/styles.css'
import GlobalProvider from '@/providers/global-provider'
import '@mantine/notifications/styles.css'
import { MainLayout } from '@/components/atoms'

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
})
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}>
                <GlobalProvider>
                    <MainLayout>{children}</MainLayout>
                </GlobalProvider>
            </body>
        </html>
    )
}
